config/routes.rb
Riceportal::Application.routes.draw do
   root  'static_pages#home'
   match '/help',    to: 'static_pages#help',    via: 'get' do
      resources :feature_requests
    end

   match '/about',   to: 'static_pages#about',   via: 'get'

   devise_for :users

   resources :purchases do
    resources :comments
   end
   
   resources :quotes do
    post :create_purchase
    resources :comments
   end

   resources :rfqs do
    post :create_quote
    resources :comments
   end

  

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :user
  has_one :purchase
  has_many :comments, as: :commentable
  validates :user_id, presence: true
  delegate :name, :email, to: :user, :prefix => true
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all(:order => "created_at DESC")
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @commentable = @quote
    @comments = @commentable.comments
    @comment = Comment.new
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)
    @quote.user_id = current_user.id
    @quote.confirm = false

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quote }
      else
        format.html { render action: 'new' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_purchase
    @quote = Quote.find(params[:quote_id])
    @quote.confirm = true
    @quote.save

    @purchase = Purchase.new
    @purchase.user_id = current_user.id
    @purchase.quote_id = @quote.id
    @purchase.price = @quote.price
    @purchase.supplier = @quote.supplier
    @purchase.commodity = @quote.commodity
    @purchase.brand = @quote.brand
    @purchase.pack_size = @quote.pack_size
    @purchase.volume = @quote.volume
    @purchase.shipment = @quote.shipment
    @purchase.save
    p @purchase

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to edit_purchase_path(@purchase), notice: 'Quote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @purchase }
      else
        format.html { render action: 'new' }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:price, :commodity, :supplier, :brand, :shipment, :volume, :purchase, :pack_size)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<div class = "well">
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :supplier %><br>
    <%= f.text_field :supplier %>
  </div>
  <div class="field">
    <%= f.label :commodity %><br>
    <%= f.text_field :commodity %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
   <div class="field">
    <%= f.label :pack_size %><br>
    <%= f.text_field :pack_size %>
  </div>
     <div class="field">
    <%= f.label :volume %><br>
    <%= f.text_field :volume %>
  </div>
  <div class="field">
    <%= f.label :shipment %><br>
    <%= f.text_area :shipment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/quotes/_links.html.erb
<div class="btn-group">
 
<%= link_to_unless(@quote.confirm?, 'Edit', edit_quote_path(@quote), class: "btn btn-default") do |p|
 link_to('Cannot Edit', '#', class: "btn btn-default disabled") end %>
<%= link_to_unless(@quote.confirm?, 'Confirm Purchase', "#{@quote.id}/create_purchase", method: :create_purchase, data: {confirm: 'Are you sure you want to confirm this quote and record a purchase?'}, class: "btn btn-default") do |p|
    link_to('Already Confirmed', '#', class: "btn btn-default disabled") end %>
 <%= link_to 'New Quote', new_quote_path, class: "btn btn-default" %>
</div>

app/views/quotes/create.html.erb
<div class = "show-elements">

<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back to Quotes', quotes_path %>

</div>

app/views/quotes/edit.html.erb
<div class = "show-elements">

<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to '<< Back to Quote Details', @quote %> <br>
<%= link_to '<< Back to Quotes Index', quotes_path %>
</div>

app/views/quotes/index.html.erb
<h1> Rice and Grains Commodity Quotes
</h1>

<body>



<table id="quotes" class="table table-striped">
  <thead>

    <tr>
      <th>Date</th>
      <th>Commodity</th>
      <th>Price </th>
      <th>Pack Size</th>
      <th>Supplier</th>
      <th>Purchased</th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.created_at.strftime("%m/%d/%Y") %></td>
        <td><%= link_to quote.commodity, quote%></td>
        <td><%= quote.price %></td>
        <td><%= quote.pack_size %></td>
	<td><%= quote.supplier %></td>
        <td><%= t quote.confirm.class %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</body>

<br>



<%= link_to 'New Quote', new_quote_path, class: "btn btn-large btn-primary" %>

app/views/quotes/new.html.erb
<div class = "show-elements">

<h1>New quote</h1>

<%= render 'form' %>

<%= link_to '<< Back to Quotes Index', quotes_path %>
</div>

app/views/quotes/show.html.erb
<div class = "show-elements">
<%= link_to '<< Back to Quotes Index', quotes_path %> 
<h1>
  Quote Details
</h1>
<div class = "well">
<p>
  <strong>Price:</strong>
  <%= @quote.price %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @quote.supplier %>
</p>

<p>
  <strong>Commodity:</strong>
  <%= @quote.commodity %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @quote.brand %>
</p>

<p>
  <strong>Pack Size:</strong>
  <%= @quote.pack_size %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @quote.volume %>
</p>

<p>
  <strong>Shipment Details:</strong>
  <%= @quote.shipment %>
</p>

<p>
  <strong>Purchased:</strong>
  <%= t @quote.confirm.class %>
</p>

<p>
  <strong>Created At: </strong><%= @quote.created_at.strftime("%m/%d/%Y %H:%M%p") %></p>

<p>
  <strong>Created By: </strong><%= @quote.user_name %></p>


<%= render "links" %>
</div>


<%= render "comments/comments" %>
<br>
<%= render "comments/form" %>

</div>

<%= link_to '<< Back to Quotes Index', quotes_path %> 
</div>