config/routes.rb
Riceportal::Application.routes.draw do
   root  'static_pages#home'
   match '/help',    to: 'static_pages#help',    via: 'get' do
      resources :feature_requests
    end

   match '/about',   to: 'static_pages#about',   via: 'get'

   devise_for :users

   resources :purchases do
    resources :comments
   end
   
   resources :quotes do
    post :create_purchase
    resources :comments
   end

   resources :rfqs do
    post :create_quote
    resources :comments
   end

  

end

app/models/rfq.rb
class Rfq < ActiveRecord::Base
  belongs_to :user
  has_one :quote
  validates :user_id, presence: true
  delegate :name, :email, to: :user, :prefix => true
end

app/controllers/rfqs_controller.rb
class RfqsController < ApplicationController

  before_action :set_rfq, only: [:show, :edit, :update]

  # GET /rfqs
  # GET /rfqs.json
  def index
    @rfqs = Rfq.find(:all, :conditions => {:status => false})
  end

  # GET /rfqs/1
  # GET /rfqs/1.json
  def show
    @commentable = @rfq
    @comments = @commentable.comments
    @comment = Comment.new
  end

  # GET /rfqs/new
  def new
    @rfq = Rfq.new
  end

  def edit
  end

  # POST /rfqs
  # POST /rfqs.json
  def create
    @rfq = Rfq.new(rfq_params)
    @rfq.user_id = current_user.id
    @rfq.status = false
    

    respond_to do |format|
      if @rfq.save
        format.html { redirect_to @rfq, notice: 'Request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rfq }
      else
        format.html { render action: 'new' }
        format.json { render json: @rfq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rfqs/1
  # PATCH/PUT /rfqs/1.json
  def update
    respond_to do |format|
      if @rfq.update(rfq_params)
        format.html { redirect_to @rfq, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rfq.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_quote
    @rfq = Rfq.find(params[:rfq_id])
    @rfq.status = true
    @rfq.save

    @quote = Quote.new
    @quote.user_id = current_user.id
    @quote.rfq_id = @rfq.id
    @quote.commodity = @rfq.commodity
    @quote.brand = @rfq.brand
    @quote.pack_size = @rfq.pack_size
    @quote.volume = @rfq.volume
    @quote.shipment = @rfq.shipment
    @quote.save
    p @quote

    respond_to do |format|
      if @quote.save
        format.html { redirect_to edit_quote_path(@quote), notice: 'Quote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quote }
      else
        format.html { render action: 'new' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rfq
      @rfq = Rfq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rfq_params
      params.require(:rfq).permit(:commodity, :brand, :pack_size, :volume, :shipment, :user_id)
    end
end

app/helpers/rfqs_helper.rb
module RfqsHelper
end

app/views/rfqs/_form.html.erb
<div class = "well" >
  <%= form_for(@rfq) do |f| %>
  <% if @rfq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rfq.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @rfq.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :commodity %><br>
    <%= f.text_field :commodity %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :pack_size %><br>
    <%= f.text_field :pack_size %>
  </div>
  <div class="field">
    <%= f.label :volume %><br>
    <%= f.text_field :volume %>
  </div>
  <div class="field">
    <%= f.label :shipment %><br>
    <%= f.text_area :shipment %>
  </div>
  <div class="actions">
    <%= f.submit "Submit Request For Quote" %>
  </div>

  <%= f.hidden_field :user_id %> 
<% end %>
</div>

app/views/rfqs/_links.html.erb
<div class="btn-group">
 
<%= link_to 'Edit', edit_rfq_path(@rfq), class: "btn btn-default" %> 
<%= link_to 'New Request', new_rfq_path, class: "btn btn-default" %>
<%= link_to 'Add this Quote', "#{@rfq.id}/create_quote", method: :create_quote, data: {confirm: 'Are you sure you want to close this request and record a quote?'}, class: "btn btn-default" %>
</div>

app/views/rfqs/edit.html.erb
<div class = "show-elements" >
<%= link_to '<< Back to Request Details', @rfq %> <br>
<%= link_to '<< Back to RFQ Index', rfqs_path %>

  <h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to '<< Back to Request Details', @rfq %> <br>
<%= link_to '<< Back to RFQ Index', rfqs_path %>

</div>

app/views/rfqs/index.html.erb
<h1>Request for Commodity Quotes</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Commodity</th>
      <th>Brand</th>
      <th>Pack Size</th>
      <th>Volume</th>
    </tr>
  </thead>

  <tbody>
    <% @rfqs.each do |rfq| %>
      <tr>
        <td><%= rfq.created_at.strftime("%m/%d/%Y") %></td>
        <td><%= link_to rfq.commodity, rfq %></td>
        <td><%= rfq.brand %></td>
        <td><%= rfq.pack_size %></td>
        <td><%= rfq.volume %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_rfq_path, class: "btn btn-large btn-primary" %>

app/views/rfqs/new.html.erb
<div class = "show-elements">
<%= link_to '<< Back to RFQ Index', rfqs_path %>
<h1>New Request</h1>

<%= render 'form' %>

<%= link_to '<< Back to RFQ Index', rfqs_path %>
</div>

app/views/rfqs/show.html.erb
<div class="show-elements">
<%= link_to '<< Back to RFQ Index', rfqs_path %> 

<h1> RFQ Details </h1>
<div class = "well"> 
<p>
  <strong>Commodity:</strong>
  <%= @rfq.commodity %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @rfq.brand %>
</p>

<p>
  <strong>Pack size:</strong>
  <%= @rfq.pack_size %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @rfq.volume %>
</p>

<p>
  <strong>Shipment:</strong>
  <%= @rfq.shipment %>
</p>

<p>
  <strong>Created At: </strong><%= @rfq.created_at.strftime("%m/%d/%Y %H:%M%p") %></p>

<p>
  <strong>Created By: </strong><%= @rfq.user_name %></p>

<%= render 'links' %>

</div>


<%= render "comments/comments" %>
<br>
<%= render "comments/form" %>

</div>




<%= link_to '<< Back to RFQ Index', rfqs_path %> 

</div>