config/routes.rb
Riceportal::Application.routes.draw do
   root  'static_pages#home'
   match '/help',    to: 'static_pages#help',    via: 'get' do
      resources :feature_requests
    end

   match '/about',   to: 'static_pages#about',   via: 'get'

   devise_for :users

   resources :purchases do
    resources :comments
   end
   
   resources :quotes do
    post :create_purchase
    resources :comments
   end

   resources :rfqs do
    post :create_quote
    resources :comments
   end

  

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  
  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
    @commentable = @purchase
    @comments = @commentable.comments
    @comment = Comment.new
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render action: 'show', status: :created, location: @purchase }
      else
        format.html { render action: 'new' }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:quote_id, :commodity, :supplier, :price, :brand, :pack_size, :volume, :shipment_details, :po_number)
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form.html.erb
<div class = "well">
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :po_number %><br>
    <%= f.text_field :po_number %>
  </div>
  <div class="field">
    <%= f.label :commodity %><br>
    <%= f.text_field :commodity %>
  </div>
  <div class="field">
    <%= f.label :supplier %><br>
    <%= f.text_field :supplier %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :pack_size %><br>
    <%= f.text_field :pack_size %>
  </div>
  <div class="field">
    <%= f.label :volume %><br>
    <%= f.text_field :volume %>
  </div>
  <div class="field">
    <%= f.label :shipment %><br>
    <%= f.text_field :shipment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchases/_links.html.erb
<div class="btn-group">
 
<%= link_to 'Edit', edit_purchase_path(@purchase), class: "btn btn-default" %> 
<%= link_to 'New Purchase', new_purchase_path, class: "btn btn-default" %>
<%= link_to 'Quotes Index', quotes_path, class: "btn btn-default" %>
</div>

app/views/purchases/edit.html.erb
<div class = "show-elements">
  <h1>Editing Purchase</h1>

<%= render 'form' %>

<%= link_to '<< Back to Purchase Details', @purchase %>  <br>
<%= link_to '<< Back to Purchase Index', purchases_path %>
</div>

app/views/purchases/index.html.erb
<h1>Listing purchases</h1>

<table id="purchases" class="table table-striped">
  <thead>
    <tr>
      <th>PO Number</th>
      <th>Commodity</th>
      <th>Supplier</th>
      <th>Price</th>
      <th>Brand</th>
      <th>Pack size</th>
      <th>Volume</th>
      <th>Shipment Details</th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= link_to_if(purchase.po_number?, purchase.po_number, purchase) do |p|  
              link_to('Please Enter PO Number', purchase) end %></td>
        <td><%= purchase.commodity %></td>
        <td><%= purchase.supplier %></td>
        <td><%= purchase.price %></td>
        <td><%= purchase.brand %></td>
        <td><%= purchase.pack_size %></td>
        <td><%= purchase.volume %></td>
        <td><%= purchase.shipment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path, class: "btn btn-large btn-primary"  %>

app/views/purchases/new.html.erb
<div class = "show-elements">
<h1>New purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', purchases_path %>
</div>

app/views/purchases/show.html.erb
<div class="show-elements">

<%= link_to '<< Back to Purchase Index', purchases_path %>
<h1> Purchase Details </h1>
<div class = "well">
<p>
  <strong>Po number:</strong>
  <%= @purchase.po_number %>
</p>

<p>
  <strong>Commodity:</strong>
  <%= @purchase.commodity %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @purchase.supplier %>
</p>

<p>
  <strong>Price:</strong>
  <%= @purchase.price %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @purchase.brand %>
</p>

<p>
  <strong>Pack size:</strong>
  <%= @purchase.pack_size %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @purchase.volume %>
</p>

<p>
  <strong>Shipment details:</strong>
  <%= @purchase.shipment %>
</p>
<%= render 'links' %>

</div>

<%= render "comments/comments" %>
<br>
<%= render "comments/form" %>

</div>

<%= link_to '<< Back to Purchase Index', purchases_path %>