config/routes.rb
Riceportal::Application.routes.draw do
   root  'static_pages#home'
   match '/help',    to: 'static_pages#help',    via: 'get' do
      resources :feature_requests
    end

   match '/about',   to: 'static_pages#about',   via: 'get'

   devise_for :users

   resources :purchases do
    resources :comments
   end
   
   resources :quotes do
    post :create_purchase
    resources :comments
   end

   resources :rfqs do
    post :create_quote
    resources :comments
   end

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    All content copyright Otis McAllister, 2014
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "OM Rice Portal", root_path, id: "logo" %>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Tools <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Request Quote", rfqs_path %></li>
                <li><%= link_to "Quotes", quotes_path %></li>
                <li><%= link_to "Purchases", purchases_path %></li>
                <li class="disabled"><%= link_to "Freight", '#' %></li>
              </ul>
        </li>
        <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Resources <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li class = "disabled"><%= link_to "Price Sheets", '#', class: 'disabled' %></li>
                <li class = "disabled"><%= link_to "Sales Sheets", '#', class: 'disabled' %></li>
                <li class = "disabled"><%= link_to "Photos", '#', class: 'disabled' %></li>
              </ul>
        </li>
        <li><%= link_to "Help", help_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
        <% if user_signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
        <li>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        </li>
      </ul>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class = "col-md-3">
  <div class="bs-sidebar hidden-print affix" role="complementary">
           <p> things will go here </p>
          </div>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
	<%= render 'layouts/header' %>
    <main role="main">
    <div class="container">
      <div class="col-md-12" role="main">
        <%= render 'layouts/messages' %>
      <%= yield %>
      </div>
    </div>
  </main>
       <%= render 'layouts/footer' %>
  </body>
</html>